---
- name: set location of org.eclipse.ui.ide.pref
  set_fact:
    eclipse_ui_ide_pref: "{{ eclipse_unpack_dir }}/configuration/.settings/org.eclipse.ui.ide.prefs"

- name: check if org.eclipse.ui.ide.prefs exists
  stat:
    path: "{{ eclipse_ui_ide_pref }}"
  register: eclipse_ui_ide_pref_stat

- name: Configure settings/org.eclipse.ui.ide.prefs SHOW_WORKSPACE_SELECTION_DIALOG
  lineinfile:
    dest: "{{ eclipse_unpack_dir }}/configuration/.settings/org.eclipse.ui.ide.prefs"
    state: present
    backup: no
    regexp: "^SHOW_WORKSPACE_SELECTION_DIALOG=.*$"
    line: "SHOW_WORKSPACE_SELECTION_DIALOG=false"
  when: eclipse_ui_ide_pref_stat.stat.exists
  tags: [eclipse_config]

- name: Configure settings/org.eclipse.ui.ide.prefs RECENT_WORKSPACES
  lineinfile:
    dest: "{{ eclipse_unpack_dir }}/configuration/.settings/org.eclipse.ui.ide.prefs"
    state: present
    backup: no
    regexp: "^RECENT_WORKSPACES=.*$"
    line: "RECENT_WORKSPACES="
  when: eclipse_ui_ide_pref_stat.stat.exists
  tags: [eclipse_config]
