---
- name: Create install directory
  file:
    dest: "{{ eclipse_install_dir }}"
    state: directory
  tags: [eclipse]

- name: set directory where the archive will be extracted to
  set_fact:
#    eclipse_unpack_dir:   "{{ eclipse_install_dir ~ '/' ~ eclipse_defaults.distros[eclipse_distro].version }}"
    eclipse_unpack_dir: "{{ eclipse_install_dir ~ '/eclipse' }}"

- debug:
    var: eclipse_unpack_dir

- name: unpack archive from master
  unarchive:
    src:     "{{ master_download_folder ~ '/' ~ eclipse_file_tar }}"
    dest:    "{{ eclipse_install_dir }}"
    creates: "{{ eclipse_unpack_dir }}"
#    extra_opts: ["--strip-components=1"]
  tags: [eclipse]

- name: install graphics libraries required
  apt: name="{{item}}" state=present
  with_items:
    - libgtk-3-0
#    - libcanberra-gtk-module # for sound?
    - libswt-gtk-3-jni
    - libswt-gtk-3-java
  when: ansible_distribution == 'Ubuntu'
