---
- name: create plugins install command
  set_fact:
    plugin_install_command: "{{ eclipse_unpack_dir}}/eclipse -nosplash \
      -application org.eclipse.equinox.p2.director \
      -destination {{ eclipse_unpack_dir}}"
  tags: [eclipse_plugins]

#Pydev
- name: Install python pexpect for adding Pydev certificat
  apt: pkg={{ item }} state=present
  with_items:
    - python-pexpect
  when: ansible_distribution == 'Debian' and "'pydev' in eclipse.plugins_enabled"
  tags: [eclipse_plugins]

#todo for RehHat : sudo yum install pexpect.noarch

- name: Transfer eclipse Pydev certificate
  copy: src=add_pydev_certificate.py dest={{ eclipse_dir_tmp }} mode=0777 force=yes owner="{{eclipse_owner}}" group="{{eclipse_group}}"
  when: "'pydev' in eclipse.plugins_enabled"
  tags: [eclipse_plugins]

- name: Add eclipse Pydev certificate
  command: python {{ eclipse_dir_tmp }}/add_pydev_certificate.py
  when: "'pydev' in eclipse.plugins_enabled"
  tags: [eclipse_plugins]

#Subclipse
- name: Install JavaHL for subclipse
  apt: pkg={{ item }} state=present
  with_items:
    - libsvn-java
  when: ansible_distribution == 'Debian' and "'subclipse' in eclipse.plugins_enabled"
  tags: [eclipse_plugins]

# all plugins
- name: list eclipse plugins to install
  debug:
    msg: "{{ eclipse.plugins_enabled | join(',') }}"
  tags: [eclipse_plugins]

- name: Install eclipse plugins
  become:      true
  become_user: "{{ eclipse.owner }}"
  command: "{{plugin_install_command}} \
    -repository \
    {{ (['http://download.eclipse.org/releases/' + eclipse_distro] + eclipse.plugins[item].repositories) | join(',') }} \
    -installIU \
    {{ eclipse.plugins[item].install_units | join(',') }}"
  with_items: '{{ eclipse.plugins_enabled }}'
  when: eclipse.plugins[item] is defined
  ignore_errors: True
  tags: [eclipse_plugins]
